name: FirstSpawn
version: '${project.version}'
main: io.mckenz.firstspawn.FirstSpawn
api-version: '1.21'
folia-supported: true
description: Ensures new players spawn at the correct coordinates
commands:
  firstspawn:
    description: Main command for FirstSpawn plugin
    usage: |
      /<command> set - Sets the first spawn location to your position
      /<command> status - Shows current spawn location
      /<command> test - Test teleport to spawn location
      /<command> toggle - Enable/disable the plugin
      /<command> reload - Reload the configuration
      /<command> debug - Toggle debug mode
    aliases: [fs]
permissions:
  firstspawn.admin:
    description: Gives access to all FirstSpawn commands
    default: op
    children:
      firstspawn.set: true
      firstspawn.status: true
      firstspawn.test: true
      firstspawn.toggle: true
      firstspawn.reload: true
      firstspawn.debug: true
      firstspawn.update: true
  firstspawn.set:
    description: Allows setting the first spawn location
    default: op
  firstspawn.status:
    description: Allows checking the plugin status
    default: op
  firstspawn.test:
    description: Allows testing the first spawn location
    default: op
  firstspawn.toggle:
    description: Allows enabling/disabling the plugin
    default: op
  firstspawn.reload:
    description: Allows reloading the plugin configuration
    default: op
  firstspawn.debug:
    description: Allows toggling debug mode
    default: op
  firstspawn.update:
    description: Allows receiving update notifications
    default: op 